### ISSUE TITLE
bigquery with form encoded data does not work

### ISSUE THREAD

**Issue by vsudilov** [adsabs/solr-service#4]
after some digging with @jonnybazookatone , it seems that the bigquery resource does not work as expected. Namely, request.data will always be empty if the content-type is set correctly to form-encoded. Instead the function should use request.form and/or do something to take into account the incoming content-type beyond what flask does.

It also looks like the test cases do not cover this at the moment.

**Comment by jonnybazookatone** [comment]
So, I believe the puzzle is solved and that the bigquery behaves as expected. When sending a curl request, you have to prefix the data with a $ in a bash terminal. For example,

curl -H "Content-Type: big-query/csv" -H "Authorization: token" 'http://localhost:8000/bigquery?q=*:*&wt=json&fl=bibcode&fq=%7B%21bitset%7D" -X POST -d 'bibcode\n1907AN....174...59.\n1908PA.....16..445.\n1989LNP...334..242S\n'

will end up passing 'bibcode\\n1907AN....174...59.\\n1908PA.....16..445.\\n1989LNP...334..242S\\n, whereas I believe it wants actual escape characters. This is achieved by the $ prefix:

curl -H "Content-Type: big-query/csv" -H "Authorization: token" 'http://localhost:8000/bigquery?q=*:*&wt=json&fl=bibcode&fq=%7B%21bitset%7D" -X POST -d $'bibcode\n1907AN....174...59.\n1908PA.....16..445.\n1989LNP...334..242S\n'

So I think the original issue is non-existent and can be closed. However, I think it may be more intuitive to include a few additions to the end point if no one has problems:

  1. Add `{!bitset}` automatically, as it won't work otherwise, and get rid of the 400 error
  2. Add the `'Content-Type': 'big-query/csv'` to the header anyway, as with any other header it seems to crash when I send it to solr

**Comment by jonnybazookatone** [comment]
So that I don't forget to implement the following;

`{!bitset}` can be placed as a default, but overridden if provided by the user, as there may be alternatives.

Update the documents to reflect these changes.

**Comment by jonnybazookatone** [comment]
@romanchyla: is there a reason the following would break any requests?

```python
        if 'fq' not in query or '!bitset' not in query.get('fq', []):
            # Default to a sensible settings
            query['fq'] = '{!biset}'
```

or is it possible that they have something sensible within 'fq' that needs the addition of '{!bitset}'?

**Comment by romanchyla** [comment]
if you set fq with '{!bitset}' you should make sure there is also the content-stream there

btw: '!bitset' not in query.get('fq') will always be false ;)

**Comment by jonnybazookatone** [comment]
Can you give a bit more info on what you mean by the content-stream, I don't think I understand.

Ah, yes, I didn't realise it was an array, so even more simply
```python
if not filter(lambda q: '!bitset' in q, query.get('fq', [])):
  query['fq'] = '{!bitset}'
```
that should cover both `fq` not existing and `{!bitset}` not within `query['fq']` if I'm not stupid....

**Comment by jonnybazookatone** [comment]
This would however, override anything that the user placed in there.

```python
if not 'fq' in query:
  query['fq] = ['{!bitset}']
elif filter(lambda q: '!biset! in q, query['fq']):
  query['fq'].append('{!bitset}')
```

I want there to be a one liner, but I can't think of one?

**Comment by romanchyla** [comment]
nope, you can have multiple fq's and only one of them may (or may not be bitset), this should solve both

```
if len(filter(lambda x: '!bitset' in x, query['fq'])) == 0:
  query['fq'].append('{!bitset}')
```

i hope the streams (i.e. posted files) are not ordered! (hmm, if they were, we should generate an error if !bitset is missing for one of them -- ok, let's simplify and allow just one stream per request)

**Comment by jonnybazookatone** [comment]
That will give `KeyErrors` if you don't supply `fq` at all.
```python
if not filter(lambda q: '!bitset' in q, query.get('fq', [])):
  query.setdefault('fq', []).append('{!bitset}')
```
should cover that. Is there any reason you prefer to have a `len()` operator as well? An empty list should also result false, which is the same as `len() == 0`.

**Comment by romanchyla** [comment]
there is no reason other than spending much time with javascript lately

in js the 'implicit' is bad, http://www.amazon.com/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742
